name: pyrootplots
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.9.12
    - pip
    - root
    - numpy
    - pandas
    - matplotlib
    - sphinx
    - sphinx_rtd_theme
    - sphinx-toolbox
