name: pyrootplots
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.9.5
    - pip
    - root
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - sphinx
    - sphinx_rtd_theme
    - sphinx-toolbox
    - m2r2
